
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
        - "${MYSQL_PORT}:3306"
    volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    networks:
        - migration_network

  # postgres:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   ports:
  #     - "${POSTGRES_PORT}:5432"
  #   volumes:
  #     - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
  #   networks:
  #     - migration_network

  pgloader:
    image: dimitri/pgloader
    volumes:
      - ./:/pgloader_config
    networks:
      - migration_network
    depends_on:
      - mysql
      - postgres
    environment:
      - PGLOADER_OPTS=--verbose

networks:
  migration_network:
    driver: bridge

volumes:
  mysql_data:
  postgres_data: