services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./scripts/init-mysql.sh:/docker-entrypoint-initdb.d/init-mysql.sh
      - ./dumps:/docker-entrypoint-initdb.d/dumps
    network_mode: host

  pgloader:
    image: dimitri/pgloader:latest
    platform: linux/amd64/v8
    volumes:
      - ./pgloader_config:/pgloader_config
    network_mode: host
    depends_on:
      - mysql
    environment:
      - PGLOADER_OPTS=--verbose

volumes:
  mysql_data: